"use client";

import {useCallback,useEffect,useState} from "react";
import {toast} from "sonner";
import {api,json,portalPath} from "@/lib/api";
import {useAuth} from "@/components/auth-provider";
import {Button,Card,Empty,Field,Input,PageHeader,Pill,Select,Table,TableBody,TableCell,TableHead,TableHeader,TableRow,TableWrap} from "@/components/ui";

type Teacher={user_id:string;full_name:string;email:string;status:string};
export default function TeachersPage(){const auth=useAuth();const[items,setItems]=useState<Teacher[]>([]);const[form,setForm]=useState({email:"",password:"",full_name:""});const[reset,setReset]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);
const load=useCallback(async()=>{if(!auth.session)return;const result=await api<{items:Teacher[]}>(portalPath("center","tenant","/teachers"),auth.session.access_token);setItems(result.items||[])},[auth.session]);useEffect(()=>{void load().catch((e:Error)=>toast.error(e.message))},[load]);
async function create(){if(!auth.session||busy)return;setBusy(true);try{await api(portalPath("center","tenant","/teachers"),auth.session.access_token,json("POST",form));toast.success("Teacher account yaratildi");setForm({email:"",password:"",full_name:""});await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
async function update(id:string,payload:Record<string,unknown>,message:string){if(!auth.session)return;try{await api(portalPath("center","tenant",`/teachers/${id}`),auth.session.access_token,json("PATCH",payload));toast.success(message);await load()}catch(e:any){toast.error(e.message)}}
return <><PageHeader title="Teachers" subtitle="Teacher accountlari. Teacher vocabulary yaratadi, studentlarga qo‘shimcha so‘z va vocabulary homework beradi."/><Card className="section"><div className="grid grid-3"><Field label="Full name"><Input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></Field><Field label="Email"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Temporary password"><Input type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field></div><Button className="accent section" onClick={create} disabled={busy||!form.full_name.trim()||!form.email.trim()||form.password.length<10}>{busy?"Creating…":"Add teacher"}</Button></Card><div className="section">{!items.length?<Empty>No teachers yet.</Empty>:<TableWrap><Table><TableHeader><TableRow><TableHead>Teacher</TableHead><TableHead>Email</TableHead><TableHead>Status</TableHead><TableHead>Password recovery</TableHead></TableRow></TableHeader><TableBody>{items.map(t=><TableRow key={t.user_id}><TableCell><b>{t.full_name}</b><div className="mono muted">{t.user_id.slice(0,12)}</div></TableCell><TableCell>{t.email}</TableCell><TableCell><Select value={t.status} onChange={e=>void update(t.user_id,{status:e.target.value},"Teacher status updated")}><option value="active">active</option><option value="suspended">suspended</option><option value="archived">archived</option></Select><div style={{marginTop:6}}><Pill tone={t.status==="active"?"ok":"bad"}>{t.status}</Pill></div></TableCell><TableCell><div className="row"><Input type="password" minLength={10} placeholder="10+ characters" value={reset[t.user_id]||""} onChange={e=>setReset(v=>({...v,[t.user_id]:e.target.value}))}/><Button disabled={(reset[t.user_id]||"").length<10} onClick={async()=>{await update(t.user_id,{new_password:reset[t.user_id]},"Teacher password reset; sessions revoked");setReset(v=>({...v,[t.user_id]:""}))}}>Reset</Button></div></TableCell></TableRow>)}</TableBody></Table></TableWrap>}</div></>}
