"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { api, json, portalPath } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { Button, Card, Empty, Field, Input, PageHeader, Select, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, TableWrap } from "@/components/ui";

type Catalog = { question_count: number; topic_count: number; bank_version: string };
type Assignment = { id: string; title: string; target_type: string; question_count: number; created_at: string };
type Group = { id: string; name: string };
type Student = { user_id: string; full_name: string };

export default function SATPage() {
  const auth = useAuth(); const [catalog, setCatalog] = useState<Catalog | null>(null); const [items, setItems] = useState<Assignment[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [students, setStudents] = useState<Student[]>([]); const [form, setForm] = useState({ title: "SAT Math practice", target_type: "all", target_id: "", question_count: 44 });
  const load = useCallback(async () => { if (!auth.session) return; const [c, x, g, s] = await Promise.all([api<Catalog>(portalPath("center", "sat", "/catalog"), auth.session.access_token), api<{items: Assignment[]}>(portalPath("center", "sat", "/assignments"), auth.session.access_token), api<{items: Group[]}>(portalPath("center", "tenant", "/groups"), auth.session.access_token), api<{items: Student[]}>(portalPath("center", "tenant", "/students"), auth.session.access_token)]); setCatalog(c); setItems(x.items || []); setGroups(g.items || []); setStudents(s.items || []); }, [auth.session]);
  useEffect(() => { void load().catch((error: Error) => toast.error(error.message)); }, [load]);
  const targets = useMemo(() => form.target_type === "group" ? groups : students, [form.target_type, groups, students]);
  async function create() { if (!auth.session) return; if (form.target_type !== "all" && !form.target_id) { toast.error("Target item is required"); return; } const body: Record<string, unknown> = { title: form.title, target_type: form.target_type, question_count: Number(form.question_count) }; if (form.target_type !== "all") body.target_id = form.target_id; try { await api(portalPath("center", "sat", "/assignments"), auth.session.access_token, json("POST", body)); toast.success("SAT assignment created"); await load(); } catch (error: any) { toast.error(error.message); } }
  return <><PageHeader title="SAT Math" subtitle="8,000 original English SAT-style practice items: 80 topics × 100 variants."/><div className="grid grid-3 section"><Card><div className="muted">Questions</div><div className="metric">{catalog?.question_count ?? 8000}</div></Card><Card><div className="muted">Topics</div><div className="metric">{catalog?.topic_count ?? 80}</div></Card><Card><div className="muted">Bank version</div><div className="metric" style={{fontSize:19}}>{catalog?.bank_version || "—"}</div></Card></div><Card className="section"><div className="grid grid-3"><Field label="Title"><Input value={form.title} onChange={(e) => setForm({...form,title:e.target.value})}/></Field><Field label="Target"><Select value={form.target_type} onChange={(e) => setForm({...form,target_type:e.target.value,target_id:""})}><option value="all">All</option><option value="group">Group</option><option value="student">Student</option></Select></Field>{form.target_type !== "all" && <Field label="Target item"><Select value={form.target_id} onChange={(e) => setForm({...form,target_id:e.target.value})}><option value="">Select…</option>{targets.map((item:any) => <option key={item.id || item.user_id} value={item.id || item.user_id}>{item.name || item.full_name}</option>)}</Select></Field>}<Field label="Questions"><Input type="number" min={10} max={80} value={form.question_count} onChange={(e) => setForm({...form,question_count:Number(e.target.value)})}/></Field></div><Button className="accent section" onClick={() => void create()}>Create SAT assignment</Button></Card><div className="section">{items.length === 0 ? <Empty>No SAT assignments yet.</Empty> : <TableWrap><Table><TableHeader><TableRow><TableHead>Title</TableHead><TableHead>Target</TableHead><TableHead>Questions</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell>{item.title}</TableCell><TableCell>{item.target_type}</TableCell><TableCell>{item.question_count}</TableCell><TableCell>{new Date(item.created_at).toLocaleDateString()}</TableCell></TableRow>)}</TableBody></Table></TableWrap>}</div></>;
}
